### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by aleexnl** [aleexnl/trip-count#10]
## Resume
HOME page mostra una llista de viatges ordenable per data de creació o data de darrera actualització, i el botó AFEGIR VIATGE.
## ToDo

- [x] Show all trips 

- [x] Order trips order desc/asc by creation date or update date

- [x]  Button to add trips
