### ISSUE TITLE
Invitations page

### ISSUE THREAD

**Issue by aleexnl** [aleexnl/trip-count#12]
## Resume
 Pàgina INVITACIONS: Ens apareix el nom del viatge en el que estem treballant i un formulari amb un camp per afegir email d'invitació.
## ToDo

- [x] Actual trip name

- [x] email input field to send invitation

- [x] "+" button to add fields to input mails

- [x] Send invitations button
