### ISSUE TITLE
Database analisys

### ISSUE THREAD

**Issue by aleexnl** [aleexnl/trip-count#2]
## Resume
Fer anàlisi de les taules de la BD necessària per a l'aplicació. Al menys haurà de tenir: usuaris, viatges, despeses, invitacions, amistats
## TODO

- [x] Taula de usuaris

- [x] Taula de despeses

- [x] Taula de viatges

- [x] Taula de invitacions

- [x] Taula de amistats
